repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettify TypeScript
        language: system
        entry: node_modules/.bin/prettier
        types: [file, ts]
        pass_filenames: true
      - id: eslint
        name: Lint TypeScript
        language: system
        entry: node_modules/.bin/eslint
        types: [file, ts]
        pass_filenames: true
